-- AlterTable Companies
ALTER TABLE "companies"
  ADD COLUMN IF NOT EXISTS "address" TEXT,
  ADD COLUMN IF NOT EXISTS "city" TEXT,
  ADD COLUMN IF NOT EXISTS "district" TEXT,
  ADD COLUMN IF NOT EXISTS "state" TEXT,
  ADD COLUMN IF NOT EXISTS "pincode" TEXT,
  ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'India',
  ADD COLUMN IF NOT EXISTS "phone" TEXT,
  ADD COLUMN IF NOT EXISTS "email" TEXT,
  ADD COLUMN IF NOT EXISTS "is_gst_registered" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "gstin" TEXT,
  ADD COLUMN IF NOT EXISTS "pan" TEXT,
  ADD COLUMN IF NOT EXISTS "bank_name" TEXT,
  ADD COLUMN IF NOT EXISTS "account_number" TEXT,
  ADD COLUMN IF NOT EXISTS "ifsc_code" TEXT,
  ADD COLUMN IF NOT EXISTS "upi_id" TEXT,
  ADD COLUMN IF NOT EXISTS "default_tax_rate" DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "tax_inclusive" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable Customers
ALTER TABLE "customers"
  ADD COLUMN IF NOT EXISTS "is_gst_applicable" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "gstin" TEXT;

-- AlterTable Invoices
ALTER TABLE "invoices"
  ADD COLUMN IF NOT EXISTS "is_gst_applicable" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "subtotal_amount" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "tax_rate" DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "tax_amount" DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "cgst_amount" DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sgst_amount" DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "igst_amount" DECIMAL(10,2) DEFAULT 0;
